#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : python-pcre
Version  : 0.7
Release  : 9
URL      : https://files.pythonhosted.org/packages/9d/af/61435bd163f01fe3709fca9b1f79e4978d8089ee671d2e004fc85e10de29/python-pcre-0.7.tar.gz
Source0  : https://files.pythonhosted.org/packages/9d/af/61435bd163f01fe3709fca9b1f79e4978d8089ee671d2e004fc85e10de29/python-pcre-0.7.tar.gz
Summary  : Python PCRE bindings
Group    : Development/Tools
License  : BSD-3-Clause
Requires: python-pcre-license = %{version}-%{release}
Requires: python-pcre-python = %{version}-%{release}
Requires: python-pcre-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pcre-dev
BuildRequires : pytest

%description
python-pcre
===========
Python bindings for PCRE regex engine.
Requirements
------------

%package license
Summary: license components for the python-pcre package.
Group: Default

%description license
license components for the python-pcre package.


%package python
Summary: python components for the python-pcre package.
Group: Default
Requires: python-pcre-python3 = %{version}-%{release}

%description python
python components for the python-pcre package.


%package python3
Summary: python3 components for the python-pcre package.
Group: Default
Requires: python3-core
Provides: pypi(python_pcre)

%description python3
python3 components for the python-pcre package.


%prep
%setup -q -n python-pcre-0.7
cd %{_builddir}/python-pcre-0.7

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1585316276
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
pytest || :
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/python-pcre
cp %{_builddir}/python-pcre-0.7/LICENSE %{buildroot}/usr/share/package-licenses/python-pcre/6750d6ca102979a7ce9e5e3521753311084b0b57
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/python-pcre/6750d6ca102979a7ce9e5e3521753311084b0b57

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
